<?php
return array(
	'pager' => array(	// pagination setting
		'tpl' => 'Public:pager',
		'param_name' => 'page',
		'page' => 1,
		'page_size' => 30,
		'page_sum' => 0,
		'record_sum' => 0,
		'items' => array(),
		'params' => array()
	),
	'defect_location'=>array(
	     array('abbreviation'=>'AS','name'=>'AIS'),
		 array('abbreviation'=>'AP','name'=>'APPLIQUE'),
		 array('abbreviation'=>'AN','name'=>'APRON'),
		 array('abbreviation'=>'AR','name'=>'ARM'),
		 array('abbreviation'=>'BK','name'=>'BACK'),
		 array('abbreviation'=>'BA','name'=>'BACK SLAT'),
		 array('abbreviation'=>'BS','name'=>'BASE/BASE STRIP'),
		 array('abbreviation'=>'BR','name'=>'BED RAIL'),
		 array('abbreviation'=>'BL','name'=>'BLOCKS'),
		 array('abbreviation'=>'BT','name'=>'BOTTOM'),
		 array('abbreviation'=>'BF','name'=>'BUN FOOT'),
		 array('abbreviation'=>'BU','name'=>'BUTTON'),
		 array('abbreviation'=>'ch','name'=>'CORD HOLE'),
		 array('abbreviation'=>'CN','name'=>'CORNER'),
		 array('abbreviation'=>'CV','name'=>'COVER'),
		 array('abbreviation'=>'CR','name'=>'CROWN'),
		 array('abbreviation'=>'CU','name'=>'CUSHION'),
		 array('abbreviation'=>'CC','name'=>'CUSHION COVER'),
		 array('abbreviation'=>'CO','name'=>'CUSHION FOAM'),
		 array('abbreviation'=>'DK','name'=>'DECKING'),
		 array('abbreviation'=>'DV','name'=>'DIVIDER'),
		 array('abbreviation'=>'DR','name'=>'DOOR'),
		 array('abbreviation'=>'DW','name'=>'DRAWER'),
		 array('abbreviation'=>'DF','name'=>'DRAWER FRONT'),
		 array('abbreviation'=>'DG','name'=>'DRAWER GLIDE / RAIL'),
		 array('abbreviation'=>'DC','name'=>'DUSTCOVER'),
		 array('abbreviation'=>'ED','name'=>'EDGE'),
		 array('abbreviation'=>'EB','name'=>'EDGE BAND'),
		 array('abbreviation'=>'FB','name'=>'FABRIC'),
		 array('abbreviation'=>'FA','name'=>'FABRIC'),
		 array('abbreviation'=>'FI','name'=>'FINISH'),
		 array('abbreviation'=>'FN','name'=>'FINISH'),
		 array('abbreviation'=>'FM','name'=>'FRAME'),
		 array('abbreviation'=>'FP','name'=>'FRONT PANEL'),
		 array('abbreviation'=>'GD','name'=>'GLASS DOOR'),
		 array('abbreviation'=>'GP','name'=>'GLASS PANEL'),
		 array('abbreviation'=>'GR','name'=>'GLASS RETAINER / CLIP'),
		 array('abbreviation'=>'GS','name'=>'GLASS SHELF'),
		 array('abbreviation'=>'GT','name'=>'GLASS TOP'),
		 array('abbreviation'=>'HA','name'=>'HANDLE'),
		 array('abbreviation'=>'HT','name'=>'HANG TAG'),
		 array('abbreviation'=>'HW','name'=>'HARDWARE'),
		 array('abbreviation'=>'HG','name'=>'HINGE'),
		 array('abbreviation'=>'HL','name'=>'HOLE PLUGS'),
		 array('abbreviation'=>'HP','name'=>'HOOPS'),
		 array('abbreviation'=>'KB','name'=>'KNOB'),
		 array('abbreviation'=>'KN','name'=>'KNOT'),
		 array('abbreviation'=>'LA','name'=>'LABEL'),
		 array('abbreviation'=>'LS','name'=>'LAMPSHADE'),
		 array('abbreviation'=>'LL','name'=>'LAW LABEL'),
		 array('abbreviation'=>'LF','name'=>'LEAF'),
		 array('abbreviation'=>'LG','name'=>'LEGS'),
		 array('abbreviation'=>'LI','name'=>'LIGHT FIXTURE'),
		 array('abbreviation'=>'MG','name'=>'MAGNETS'),
		 array('abbreviation'=>'MA','name'=>'MATTRESS (SLEEPER)'),
		 array('abbreviation'=>'MM','name'=>'MECHANISM'),
		 array('abbreviation'=>'MT','name'=>'METAL TACKSTRIP'),
		 array('abbreviation'=>'MR','name'=>'MIRROR'),
		 array('abbreviation'=>'MW','name'=>'MOLDING'),
		 array('abbreviation'=>'MO','name'=>'MOTOR'),
		 array('abbreviation'=>'N/','name'=>'NOT APPLICABLE'),
		 array('abbreviation'=>'BP','name'=>'OBS BACK PANEL'),
		 array('abbreviation'=>'BE','name'=>'OBS BINDING TAPE'),
		 array('abbreviation'=>'BO','name'=>'OBS BORDER'),
		 array('abbreviation'=>'FT','name'=>'OBS FOOTREST / STRETCHER'),
		 array('abbreviation'=>'FR','name'=>'OBS FRONT RAIL'),
		 array('abbreviation'=>'AI','name'=>'OBS INSIDE ARM (UPHOLSTERY)'),
		 array('abbreviation'=>'AO','name'=>'OBS OUTSIDE ARM (UPHOLSTERY)'),
		 array('abbreviation'=>'TL','name'=>'OBS TABLE LEAF'),
		 array('abbreviation'=>'TF','name'=>'OBS TOP FRONT RAIL'),
		 array('abbreviation'=>'PK','name'=>'PACK'),
		 array('abbreviation'=>'PD','name'=>'PAD'),
		 array('abbreviation'=>'PT','name'=>'PALLET'),
		 array('abbreviation'=>'PA','name'=>'PANEL'),
		 array('abbreviation'=>'PE','name'=>'PEDESTAL'),
		 array('abbreviation'=>'PL','name'=>'PILLOW'),
		 array('abbreviation'=>'PS','name'=>'POST'),
		 array('abbreviation'=>'PR','name'=>'PROFILE'),
		 array('abbreviation'=>'PH','name'=>'PULL HANDLE'),
		 array('abbreviation'=>'RL','name'=>'RAIL'),
		 array('abbreviation'=>'RC','name'=>'RELIEF CUT'),
		 array('abbreviation'=>'SS','name'=>'SEAM/JOINT'),
		 array('abbreviation'=>'SC','name'=>'SEAT'),
		 array('abbreviation'=>'SH','name'=>'SHELF'),
		 array('abbreviation'=>'SD','name'=>'SIDE'),
		 array('abbreviation'=>'SK','name'=>'SKIRT'),
		 array('abbreviation'=>'SL','name'=>'SLAT'),
		 array('abbreviation'=>'SP','name'=>'SPINDLES'),
		 array('abbreviation'=>'SG','name'=>'SPRING'),
		 array('abbreviation'=>'ST','name'=>'STRETCHER'),
		 array('abbreviation'=>'SU','name'=>'SURGING'),
		 array('abbreviation'=>'SW','name'=>'SWITCH / WIRING'),
		 array('abbreviation'=>'TT','name'=>'T-MOULDING'),
		 array('abbreviation'=>'TG','name'=>'TABLE GLIDES / SLIDES'),
		 array('abbreviation'=>'TI','name'=>'TILES'),
		 array('abbreviation'=>'TP','name'=>'TOP'),
		 array('abbreviation'=>'TR','name'=>'TRIM'),
		 array('abbreviation'=>'VN','name'=>'VENEER'),
		 array('abbreviation'=>'WL','name'=>'WELD'),
		 array('abbreviation'=>'WU','name'=>'WHOLE UNIT'),
		 array('abbreviation'=>'WR','name'=>'WINE RACK',)
    ),
	'defect_code'=>array(
		array('abbreviation'=>'BL','name'=>'BLISTERS'),
		array('abbreviation'=>'BI','name'=>'BODY IMPRESSION'),
		array('abbreviation'=>'BR','name'=>'BROKEN'),
		array('abbreviation'=>'BW','name'=>'BROKEN WELD'),
		array('abbreviation'=>'BT','name'=>'BURNT'),
		array('abbreviation'=>'CE','name'=>'CHECKING'),
		array('abbreviation'=>'CH','name'=>'CHIPPED'),
		array('abbreviation'=>'CF','name'=>'CHIPPED FINISH'),
		array('abbreviation'=>'CL','name'=>'CLOUDY'),
		array('abbreviation'=>'CV','name'=>'COLOR VARIATION'),
		array('abbreviation'=>'CR','name'=>'CRACKED'),
		array('abbreviation'=>'DN','name'=>'DENT'),
		array('abbreviation'=>'DQ','name'=>'DESIGN QUESTION'),
		array('abbreviation'=>'DT','name'=>'DIRT'),
		array('abbreviation'=>'DW','name'=>'DRILLED WRONG'),
		array('abbreviation'=>'DL','name'=>'DULL FINISH'),
		array('abbreviation'=>'XC','name'=>'END CONSUMER ISSUES'),
		array('abbreviation'=>'EG','name'=>'EXCESS GLUE'),
		array('abbreviation'=>'FL','name'=>'FABRIC FLAW'),
		array('abbreviation'=>'FP','name'=>'FINGER PRINTS'),
		array('abbreviation'=>'FT','name'=>'FLAT'),
		array('abbreviation'=>'FC','name'=>'FOAM COVERAGE INCOMPLETE'),
		array('abbreviation'=>'GS','name'=>'GAPS'),
		array('abbreviation'=>'GL','name'=>'GLUE ISSUES'),
		array('abbreviation'=>'GG','name'=>'GOUGED'),
		array('abbreviation'=>'GR','name'=>'GOVERMENT REGULATION'),
		array('abbreviation'=>'HF','name'=>'HARD FOAM'),
		array('abbreviation'=>'HS','name'=>'HIGH SHEEN'),
		array('abbreviation'=>'IC','name'=>'IMPROPER CONSTRUCTION'),
		array('abbreviation'=>'IL','name'=>'IMPROPER TAILORING'),
		array('abbreviation'=>'IT','name'=>'IMPROPER TOUCH-UP'),
		array('abbreviation'=>'LS','name'=>'LOOSE'),
		array('abbreviation'=>'LT','name'=>'LOOSE THREAD'),
		array('abbreviation'=>'LP','name'=>'LUMPS'),
		array('abbreviation'=>'MG','name'=>'MISSING'),
		array('abbreviation'=>'MO','name'=>'MOLD'),
		array('abbreviation'=>'OD','name'=>'ODOR'),
		array('abbreviation'=>'OS','name'=>'OUT OF SQUARE'),
		array('abbreviation'=>'PW','name'=>'PACKED WRONG'),
		array('abbreviation'=>'PM','name'=>'PACKING MARKS'),
		array('abbreviation'=>'PF','name'=>'PEELING FINISH'),
		array('abbreviation'=>'PI','name'=>'PILLING'),
		array('abbreviation'=>'PO','name'=>'POPPING'),
		array('abbreviation'=>'QI','name'=>'QUALITY ISSUES'),
		array('abbreviation'=>'RC','name'=>'RAC RP ELECTRONIC CODE'),
		array('abbreviation'=>'RT','name'=>'ROTTEN WOOD'),
		array('abbreviation'=>'RG','name'=>'ROUGH'),
		array('abbreviation'=>'RB','name'=>'RUB MARK'),
		array('abbreviation'=>'SR','name'=>'SAGS / RUNS'),
		array('abbreviation'=>'ST','name'=>'SAND THRU'),
		array('abbreviation'=>'SH','name'=>'SCRATCHED'),
		array('abbreviation'=>'SB','name'=>'SCREW  BUMP/NAIL/STAPLE'),
		array('abbreviation'=>'SS','name'=>'SEASONAL SPLIT'),
		array('abbreviation'=>'SE','name'=>'SEPARATED SEAMS'),
		array('abbreviation'=>'SI','name'=>'SHRINKAGE PANEL'),
		array('abbreviation'=>'SK','name'=>'SKIPPED STICHES'),
		array('abbreviation'=>'SG','name'=>'SNAG / HOLE'),
		array('abbreviation'=>'SO','name'=>'SOILED'),
		array('abbreviation'=>'SU','name'=>'SPRUNG'),
		array('abbreviation'=>'SQ','name'=>'SQUEAKY'),
		array('abbreviation'=>'SN','name'=>'STAINED'),
		array('abbreviation'=>'SP','name'=>'STRIPPED'),
		array('abbreviation'=>'TF','name'=>'TARNISHED FINISH'),
		array('abbreviation'=>'TM','name'=>'TOOLING MARKS'),
		array('abbreviation'=>'TR','name'=>'TORN / RIPPED'),
		array('abbreviation'=>'TU','name'=>'TOUCH-UP'),
		array('abbreviation'=>'FD','name'=>'TRANSIT DAMAGE'),
		array('abbreviation'=>'UE','name'=>'UNEVEN'),
		array('abbreviation'=>'UC','name'=>'UNIT FULLY COMPLIANT'),
		array('abbreviation'=>'UF','name'=>'UNIT NOT FINISHED'),
		array('abbreviation'=>'UP','name'=>'UNIT NOT PACKED'),
		array('abbreviation'=>'UA','name'=>'UNIT UNAVAILABLE FOR REVIEW'),
		array('abbreviation'=>'VL','name'=>'VENEER LIFTING'),
		array('abbreviation'=>'WA','name'=>'WARPED'),
		array('abbreviation'=>'WH','name'=>'WORM HOLES'),
		array('abbreviation'=>'WR','name'=>'WRINKLES'),
		array('abbreviation'=>'XB','name'=>'WRONG BOX'),
		array('abbreviation'=>'WL','name'=>'WRONG LOCATION'),
		array('abbreviation'=>'WS','name'=>'WRONG SIZE'),
		array('abbreviation'=>'YE','name'=>'YELLOWING',)
    ),
		
	'inspection_position'=>array(
		'whitewood'=>'Whitewood',
		'finish'=>'Finish',
		'packing'=>'Packing',
		'warehouse'=>'Finished Goods Warehouse',
		'outofbox'=>'Out of Box',
	),
		
	'leaderboard_rank'=>60,
	
);