<?php
$apis = array();

//会员相关接口
$apis[] = array(
	'category'=>'会员相关接口',
	'api'=>array(
			'Member/login'=>array(
					'desc' => '用户登录',
					'field'=>array(
							'mobile'=>array('desc'=>'手机号码'),
							'password'=>array('desc'=>'用户密码'),
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"登录成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表登录成功，0代表登录失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/register'=>array(
					'desc' => '用户注册',
					'field'=>array(
							'mobile'=>array('desc'=>'手机号码'),
							'verify'=>array('desc'=>'验证号'),
							'password'=>array('desc'=>'登录密码'),
							'confirm_password'=>array('desc'=>'确认密码'),
							'nickname'=>array('desc'=>'昵称')
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"注册成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表注册成功，0代表注册失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setPassword'=>array(
					'desc' => '修改登录密码',
					'field'=>array(
							'password'=>array('desc'=>'原密码'),
							'new_password'=>array('desc'=>'新密码'),
							'confirm_password'=>array('desc'=>'确认密码')
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"修改登录密码成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表修改登录密码成功，0代表修改登录密码失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setPayPassword'=>array(
					'desc' => '修改支付密码',
					'field'=>array(
							'password'=>array('desc'=>'原密码'),
							'new_password'=>array('desc'=>'新密码'),
							'confirm_password'=>array('desc'=>'确认密码')
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"修改支付密码成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表修改支付密码成功，0代表修改支付密码失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setMobile'=>array(
					'desc' => '修改手机号码',
					'field'=>array(
							'mobile'=>array('desc'=>'手机号码'),
							'verify'=>array('desc'=>'验证号')
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"修改手机号码成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表修改手机号码成功，0代表修改手机号码失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/getAddress'=>array(
					'desc' => '获取地址列表',
					'type'=>'GET',
					'response'=>'{"status":1,"info":"",data:{id:1,member_id:8,consignee:"startcc",province_id:6,city_id:86,area_id:786,province_name:"广东",city_name,"梅州",area_name:"五华县",address:"cccc",mobile:15820429581,is_default:1}',
					'res_field'=>array(
						array('field'=>'id','desc'=>'地址编号'),
						array('field'=>'member_id','desc'=>'会员id'),
						array('field'=>'consignee','desc'=>'收货人'),
						array('field'=>'province_id','desc'=>'省份id'),
						array('field'=>'city_id','desc'=>'城市id'),
						array('field'=>'area_id','desc'=>'区号/县id'),
						array('field'=>'province_name','desc'=>'省份名称'),
						array('field'=>'city_name','desc'=>'城市名称'),
						array('field'=>'area_name','desc'=>'区号/县名称'),
						array('field'=>'address','desc'=>'详细地址'),
						array('field'=>'mobile','desc'=>'手机号码'),
						array('field'=>'is_default','desc'=>'是否默认地址')
					)
			),
			'Member/addAddress'=>array(
					'desc' => '添加收货地址',
					'type'=>'POST',
					'field'=>array(
							'consignee'=>array('desc'=>'收货人姓名'),
							'mobile'=>array('desc'=>'收货人手机'),
							'province_id'=>array('desc'=>'省份id'),
							'province_name'=>array('desc'=>'省份名称'),
							'city_id'=>array('desc'=>'城市id'),
							'city_name'=>array('desc'=>'城市名称'),
							'area_id'=>array('desc'=>'区号/县id'),
							'area_name'=>array('desc'=>'区号/县名称'),
							'address'=>array('desc'=>'详细地址'),
					),
					'response'=>'{"status":1,"info":"添加收货地址成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表添加收货地址成功，0代表添加收货地址失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setAddress'=>array(
					'desc' => '修改收货地址',
					'type'=>'POST',
					'field'=>array(
							'address_id'=>array('desc'=>'地址id编号'),
							'consignee'=>array('desc'=>'收货人姓名'),
							'mobile'=>array('desc'=>'收货人手机'),
							'province_id'=>array('desc'=>'省份id'),
							'province_name'=>array('desc'=>'省份名称'),
							'city_id'=>array('desc'=>'城市id'),
							'city_name'=>array('desc'=>'城市名称'),
							'area_id'=>array('desc'=>'区号/县id'),
							'area_name'=>array('desc'=>'区号/县名称'),
							'address'=>array('desc'=>'详细地址'),
					),
					'response'=>'{"status":1,"info":"修改收货地址成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表修改收货地址成功，0代表修改收货地址失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/deleteAddress'=>array(
					'desc' => '删除收货地址',
					'type'=>'POST',
					'field'=>array(
							'address_id'=>array('desc'=>'地址id编号')
					),
					'response'=>'{"status":1,"info":"删除收货地址成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表删除收货地址成功，0代表删除收货地址失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setDefaultAddress'=>array(
					'desc' => '设置默认收货地址',
					'type'=>'POST',
					'field'=>array(
							'address_id'=>array('desc'=>'地址id编号')
					),
					'response'=>'{"status":1,"info":"设置默认收货地址成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表设置默认收货地址成功，0代表设置默认收货地址失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setBindMember'=>array(
					'desc' => '绑定会员',
					'type'=>'POST',
					'field'=>array(
							'bind_member'=>array('desc'=>'会员卡号')
					),
					'response'=>'{"status":1,"info":"绑定会员成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表绑定会员成功，0代表绑定会员失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/loginOut'=>array(
					'desc' => '退出帐号',
					'type'=>'GET',
					'response'=>'{"status":1,"info":"退出帐号成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表退出帐号成功，0代表退出帐号失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
	 ),
);

//商品与伙拼相关接口
$apis[] = array(
	'category'=>'商品与伙拼相关接口',
	'api'=>array(
			'Goods/getGoodsByCategoryId'=>array(
					'desc' => '获取某一分类下的商品',
					'field'=>array(
							'cid'=>array('desc'=>'分类id'),
					),
					'type'=>'GET',
					'response'=>'{"status":1,"info":"",{id:1,category_id:1,production_id:1,name:"蔬菜1",price:10.00,image:201410305451ed907043a.jpg,description:"好吃的蔬菜",sale_count:0,spec:100}}',
					'res_field'=>array(
						array('field'=>'id','desc'=>'商品id'),
						array('field'=>'category_id','desc'=>'分类id'),
						array('field'=>'production_id','desc'=>'产地id'),
						array('field'=>'name','desc'=>'商品名称'),
						array('field'=>'price','desc'=>'商品价格'),
						array('field'=>'image','desc'=>'商品图片'),
						array('field'=>'description','desc'=>'商品描述'),
						array('field'=>'sale_count','desc'=>'商品销量'),
						array('field'=>'spec','desc'=>'商品规格')
					)
			),
			'Goods/getCategoryList'=>array(
					'desc' => '获取商品分类列表',
					'type'=>'GET',
					'response'=>'{"status":1,"info":"",{id:1,name:"叶菜类",image:""}}',
					'res_field'=>array(
						array('field'=>'id','desc'=>'分类id'),
						array('field'=>'name','desc'=>'分类名称'),
						array('field'=>'image','desc'=>'分类图片')
					)
			),
			'Goods/getGoodsList'=>array(
					'desc' => '获取商品列表',
					'type'=>'GET',
					'response'=>'{"status":1,"info":"",{id:1,category_id:1,production_id:1,name:"蔬菜1",price:10.00,image:201410305451ed907043a.jpg,description:"好吃的蔬菜",sale_count:0,spec:100}}',
					'res_field'=>array(
						array('field'=>'id','desc'=>'商品id'),
						array('field'=>'category_id','desc'=>'分类id'),
						array('field'=>'production_id','desc'=>'产地id'),
						array('field'=>'name','desc'=>'商品名称'),
						array('field'=>'price','desc'=>'商品价格'),
						array('field'=>'image','desc'=>'商品图片'),
						array('field'=>'description','desc'=>'商品描述'),
						array('field'=>'sale_count','desc'=>'商品销量'),
						array('field'=>'spec','desc'=>'商品规格')
					)
			),
			'Goods/applyGroup'=>array(
					'desc' => '申请伙拼',
					'type'=>'POST',
					'field'=>array(
							'goods_id'=>array('desc'=>'商品id'),
							'production_id'=>array('desc'=>'产地id'),
							'remark'=>array('desc'=>'个人说明'),
							'member_type'=>array('desc'=>'广而告知对象'),
					),
					'response'=>'{"status":1,"info":"提交伙拼申请信息成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表提交伙拼申请信息成功，0代表提交伙拼申请信息失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Goods/getGroupList'=>array(
					'desc' => '获取伙拼商品列表',
					'type'=>'GET',
					'field'=>array(
							'size'=>array('desc'=>'条数'),
							'order'=>array('desc'=>'排序'),
							'is_recommend'=>array('desc'=>'是否推荐：1推荐、0不推荐')
					),
					'response'=>'{"status":1,"info":"",{id:1,goods_id:1,category_id:1,production_id:3,name:"蔬菜2",description:"dddgda",price:30,min_price:15.00,min_price_spec:3000,real_price:30.00,image:"201410305451ed907043a.jpg",moq_spec:1000,sale_count:0,sale_spec:0,sale_total_count:0,sale_total_spec:0,start_time:1414684800,end_time:1418399999}}',
					'res_field'=>array(
						array('field'=>'id','desc'=>'伙拼商品id'),
						array('field'=>'goods_id','desc'=>'商品id'),
						array('field'=>'category_id','desc'=>'分类id'),
						array('field'=>'production_id','desc'=>'产地id'),
						array('field'=>'name','desc'=>'伙拼商品名称'),
						array('field'=>'description','desc'=>'伙拼商品描述'),
						array('field'=>'price','desc'=>'伙拼商品价格'),
						array('field'=>'min_price','desc'=>'伙拼商品最低价格'),
						array('field'=>'min_price_spec','desc'=>'伙拼商品最低价格对应的规格'),
						array('field'=>'real_price','desc'=>'伙拼商品实际价格'),
						array('field'=>'image','desc'=>'伙拼商品图片'),
						array('field'=>'moq_spec','desc'=>'伙拼商品起拼规格'),
						array('field'=>'sale_count','desc'=>'伙拼商品销售数量'),
						array('field'=>'sale_spec','desc'=>'伙拼商品销售规格'),
						array('field'=>'sale_total_count','desc'=>'伙拼商品总销售数量'),
						array('field'=>'sale_total_spec','desc'=>'伙拼商品总销售规格'),
						array('field'=>'start_time','desc'=>'伙拼商品开始日期'),
						array('field'=>'end_time','desc'=>'伙拼商品结束日期')
					)
			),
	)		
);
	
return $apis;