<?php
$apis = array();

//会员相关接口
$apis[] = array(
	'category'=>'会员相关接口',
	'api'=>array(
			'Member/login'=>array(
					'desc' => '用户登录',
					'field'=>array(
							'mobile'=>array('desc'=>'手机号码'),
							'password'=>array('desc'=>'用户密码'),
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"登录成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表登录成功，0代表登录失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/register'=>array(
					'desc' => '用户注册',
					'field'=>array(
							'mobile'=>array('desc'=>'手机号码'),
							'verify'=>array('desc'=>'验证号'),
							'password'=>array('desc'=>'登录密码'),
							'confirm_password'=>array('desc'=>'确认密码'),
							'nickname'=>array('desc'=>'昵称')
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"注册成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表注册成功，0代表注册失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setPassword'=>array(
					'desc' => '修改登录密码',
					'field'=>array(
							'password'=>array('desc'=>'原密码'),
							'new_password'=>array('desc'=>'新密码'),
							'confirm_password'=>array('desc'=>'确认密码')
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"修改登录密码成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表修改登录密码成功，0代表修改登录密码失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setPayPassword'=>array(
					'desc' => '修改支付密码',
					'field'=>array(
							'password'=>array('desc'=>'原密码'),
							'new_password'=>array('desc'=>'新密码'),
							'confirm_password'=>array('desc'=>'确认密码')
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"修改支付密码成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表修改支付密码成功，0代表修改支付密码失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setMobile'=>array(
					'desc' => '修改手机号码',
					'field'=>array(
							'mobile'=>array('desc'=>'手机号码'),
							'verify'=>array('desc'=>'验证号')
					),
					'type'=>'POST',
					'response'=>'{"status":1,"info":"修改手机号码成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表修改手机号码成功，0代表修改手机号码失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/getAddress'=>array(
					'desc' => '获取地址列表',
					'type'=>'GET',
					'response'=>'{"status":1,"info":"",data:{id:1,member_id:8,consignee:"startcc",province_id:6,city_id:86,area_id:786,province_name:"广东",city_name,"梅州",area_name:"五华县",address:"cccc",mobile:15820429581,is_default:1}',
					'res_field'=>array(
						array('field'=>'id','desc'=>'地址编号'),
						array('field'=>'member_id','desc'=>'会员id'),
						array('field'=>'consignee','desc'=>'收货人'),
						array('field'=>'province_id','desc'=>'省份id'),
						array('field'=>'city_id','desc'=>'城市id'),
						array('field'=>'area_id','desc'=>'区号/县id'),
						array('field'=>'province_name','desc'=>'省份名称'),
						array('field'=>'city_name','desc'=>'城市名称'),
						array('field'=>'area_name','desc'=>'区号/县名称'),
						array('field'=>'address','desc'=>'详细地址'),
						array('field'=>'mobile','desc'=>'手机号码'),
						array('field'=>'is_default','desc'=>'是否默认地址')
					)
			),
			'Member/addAddress'=>array(
					'desc' => '添加收货地址',
					'type'=>'POST',
					'field'=>array(
							'consignee'=>array('desc'=>'收货人姓名'),
							'mobile'=>array('desc'=>'收货人手机'),
							'province_id'=>array('desc'=>'省份id'),
							'province_name'=>array('desc'=>'省份名称'),
							'city_id'=>array('desc'=>'城市id'),
							'city_name'=>array('desc'=>'城市名称'),
							'area_id'=>array('desc'=>'区号/县id'),
							'area_name'=>array('desc'=>'区号/县名称'),
							'address'=>array('desc'=>'详细地址'),
					),
					'response'=>'{"status":1,"info":"添加收货地址成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表添加收货地址成功，0代表添加收货地址失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setAddress'=>array(
					'desc' => '修改收货地址',
					'type'=>'POST',
					'field'=>array(
							'address_id'=>array('desc'=>'地址id编号'),
							'consignee'=>array('desc'=>'收货人姓名'),
							'mobile'=>array('desc'=>'收货人手机'),
							'province_id'=>array('desc'=>'省份id'),
							'province_name'=>array('desc'=>'省份名称'),
							'city_id'=>array('desc'=>'城市id'),
							'city_name'=>array('desc'=>'城市名称'),
							'area_id'=>array('desc'=>'区号/县id'),
							'area_name'=>array('desc'=>'区号/县名称'),
							'address'=>array('desc'=>'详细地址'),
					),
					'response'=>'{"status":1,"info":"修改收货地址成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表修改收货地址成功，0代表修改收货地址失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/deleteAddress'=>array(
					'desc' => '删除收货地址',
					'type'=>'POST',
					'field'=>array(
							'address_id'=>array('desc'=>'地址id编号')
					),
					'response'=>'{"status":1,"info":"删除收货地址成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表删除收货地址成功，0代表删除收货地址失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setDefaultAddress'=>array(
					'desc' => '设置默认收货地址',
					'type'=>'POST',
					'field'=>array(
							'address_id'=>array('desc'=>'地址id编号')
					),
					'response'=>'{"status":1,"info":"设置默认收货地址成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表设置默认收货地址成功，0代表设置默认收货地址失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/setBindMember'=>array(
					'desc' => '绑定会员',
					'type'=>'POST',
					'field'=>array(
							'bind_member'=>array('desc'=>'会员卡号')
					),
					'response'=>'{"status":1,"info":"绑定会员成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表绑定会员成功，0代表绑定会员失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
			'Member/loginOut'=>array(
					'desc' => '退出帐号',
					'type'=>'GET',
					'response'=>'{"status":1,"info":"退出帐号成功"}',
					'res_field'=>array(
						array('field'=>'status','desc'=>'1代表退出帐号成功，0代表退出帐号失败'),
						array('field'=>'info','desc'=>'提示信息')
					)
			),
	 ),
);
	
return $apis;