<?php
return array(
	// font style 
	'font' => array(
		'content' => array(
			'setName' => 'Arial',
			'setSize' => 10
		),
	),
	// cell width
	'cell_width' => array('A','Z',15),
	
	// align : setHorizontal(left,center,right,justify), setVertical(top,center,bottom,justify)  
	'align' => array(
		  	'setHorizontal' => 'center',
	  		'setVertical' => 'center'
	),
	
	// row height
	'row_height' => 90,
	
	// cells
	'cells' =>array(
		array(
  			'office' => array('txt'=>'Office','show_type' => 'col',
  				'col' => 'office',
  				'merge_cells'=>array(1,2)
  			),
  			'market_time' => array('txt'=>'Target Time & Market','show_type' => 'fun',
  				'fun' => 'function($data){return substr($data["market_time"],0,7);};',
  				'merge_cells'=>array(1,2)
  			),
  			'vendor.vendor_name' => array('txt'=>'Vendor','show_type' => 'fun',
  				'fun' => 'function($data){return $data["vendor"]["vendor_name"];};',
  				'merge_cells'=>array(1,2)
  			),
  			'vendor.vendor_no' => array('txt'=>'Vendor#','show_type' => 'fun',
  				'fun' => 'function($data){return $data["vendor"]["vendor_no"];};',
  				'merge_cells'=>array(1,2)
  			),
	  		'category' => array('txt'=>'Category','show_type' => 'fun',
	  			'fun' => 'function($data){$category = CC("Sps/accessory.category");return $category[$data["category_id"]];};',
  				'merge_cells'=>array(1,2)
  			),
			'ashley_sku' => array('txt'=>'Ashley SKU','show_type' => 'col','col' => 'ashley_sku',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFFFC000'
  			),
			'sample_no' => array('txt'=>'Sample#','show_type' => 'col','col' => 'sample_no',
  				'merge_cells'=>array(1,2)
  			),
			'group_name' => array('txt'=>'Group Name','show_type' => 'col','col' => 'group_no',
  				'merge_cells'=>array(1,2)
  			),
	 		'image' => array('txt'=>'Image','show_type' => 'image',
				'fun' => 'function($data){return empty($data["images"])?"":APP_PATH."/Upload/sps/".$data["images"];};',
  				'merge_cells'=>array(1,2),
  				'setting' => array(
  					'setWidth' => 80,
  					'setHeight' => 107
  				)
  			),
			'status' => array('txt'=>'Status','show_type' => 'col','col' => 'go_status',
  				'merge_cells'=>array(1,2)
  			),
	 		'notes' => array('txt'=>'Notes','show_type' => 'col','col' => 'notes',
  				'merge_cells'=>array(1,2)
  			),
	 		'description' => array('txt'=>'Descriptions','show_type' => 'col','col' => 'description',
  				'merge_cells'=>array(1,2)
  			),
	 		'lead_time ' => array('txt'=>'Lead time ','show_type' => 'col','col' => 'lead_time',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'title_moq' => array('is_parent' => true,'txt'=>'MOQ','show_type' => 'txt',
	 			'merge_cells'=>array(2,1),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'finish' => array('txt'=>'Finish','show_type' => 'col','col' => 'finish',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'material' => array('txt'=>'Material','show_type' => 'col','col' => 'material',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'fragrance' => array('txt'=>'Fragrance','show_type' => 'col','col' => 'fragrance',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF',
  				'category_id' => 1// candle
  			),
	 		'burning_hours' => array('txt'=>'Burning Hours','show_type' => 'col','col' => 'burning_hours',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF',
  				'category_id' => 1// candle
  			),
	 		'ounce' => array('txt'=>'ounce(OZ)','show_type' => 'col','col' => 'ounce',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF',
  				'category_id' => 1 // candle
  			),
	 		'hamonized_tariff_no' => array('txt'=>'Hamonized Tariff#','show_type' => 'col','col' => 'hamonized_tariff_no',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'coo' => array('txt'=>'COO','show_type' => 'col','col' => 'coo',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'shipping.fob_port' => array('txt'=>'FOB Port','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["shipping"]["fob_port"];};',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'title_china' => array('is_parent' => true,'txt' => 'China',
	 			'merge_cells'=>array(12,1),
	 			'background_color'=>'FF538DD5'),
	 		'title_us' => array('is_parent' => true,'txt' => 'US',
	 			'merge_cells'=>array(13,1),
	 			'background_color'=>'FF92D050'),
	 		'title_item_dimension' => array('is_parent' => true,'txt'=>'Item dimension-overall size (Inch)',
	 			'merge_cells'=>array(3,1),
	 			'background_color'=>'FFE26B0A'),
	 		'title_unit_pack' => array('is_parent' => true,'txt'=>'Unit Pack info(pcs)',
	 			'merge_cells'=>array(2,1),
	 			'background_color'=>'FFE26B0A'),
	 		'title_master_dimension' => array('is_parent' => true,'txt'=>'Master carton dimension(Inch)',
	 			'merge_cells'=>array(3,1),
	 			'background_color'=>'FFE26B0A'),
	 		'shipping.carton_cuft' => array('txt'=>'Master carton CUFT / CTN','show_type' => 'fun',
	 			'fun' => 'function($data){return $data["shipping"]["carton_cuft"];};',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFE26B0A'
  			),
	 		'title_master_carton_weight' => array('is_parent' => true,'txt'=>'Master carton weight (LB)',
	 			'merge_cells'=>array(2,1),
	 			'background_color'=>'FFE26B0A'),
	 		'fixture1_id' => array('txt'=>'Fixture1','show_type' => 'fun',
	 			'fun' => 'function($data){$fixture1 = CC("Sps/accessory.fixture1");return $fixture1[$data["fixture1_id"]];};',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'fixture2_id' => array('txt'=>'Fixture2','show_type' => 'fun',
	 			'fun' => 'function($data){$fixture2 = CC("Sps/accessory.fixture2");return $fixture2[$data["fixture2_id"]];};',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'lifestyle_id' => array('txt'=>'Lifestyle','show_type' => 'fun',
	 			'fun' => 'function($data){$lifestyle = CC("Sps/accessory.lifestyle");return $lifestyle[$data["lifestyle_id"]];};',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'fixture1_cn_id' => array('txt'=>'China Fixture1','show_type' => 'fun',
	 			'fun' => 'function($data){$fixture1 = CC("Sps/accessory.fixture1_cn");return $fixture1[$data["fixture1_cn_id"]];};',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'fixture2_cn_id' => array('txt'=>'China Fixture2','show_type' => 'fun',
	 			'fun' => 'function($data){$fixture2 = CC("Sps/accessory.fixture2_cn");return $fixture2[$data["fixture2_cn_id"]];};',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'lifestyle_cn_id' => array('txt'=>'China Lifestyle','show_type' => 'fun',
	 			'fun' => 'function($data){$lifestyle = CC("Sps/accessory.lifestyle_cn");return $lifestyle[$data["lifestyle_cn_id"]];};',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFBFBFBF'
  			),
	 		'outer_frame' => array('txt'=>'Outer Frame','show_type' => 'col','col' => 'outer_frame',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFE26B0A',
  			),
	 		'card_type' => array('txt'=>'Card type','show_type' => 'col','col' => 'card_type',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFE26B0A',
  			),
	 		'individual_pack_type' => array('txt'=>'Individual pack type','show_type' => 'col','col' => 'individual_pack_type',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFE26B0A',
  			),
	 		'backup_pieces' => array('txt'=>'Back up pieces 3 months','show_type' => 'col','col' => 'backup_pieces',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFE26B0A',
  			),
	 		'total_pieces' => array('txt'=>'Total US & China pieces','show_type' => 'col','col' => 'total_pieces',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFE26B0A',
  			),
	 		'total_cubes' => array('txt'=>'Total Cubes','show_type' => 'col','col' => 'total_cubes',
  				'merge_cells'=>array(1,2),
  				'background_color'=>'FFE26B0A',
  			),
  		),
  		array(
  			'moq' => array('show_type' => 'col','txt'=>'Sets',
  				'col' => 'moq', 
  				'parent' => 'title_moq',
  				'background_color'=>'FFBFBFBF'),
  			'moq_set_of' => array('show_type' => 'col','txt'=>'Set of (PCS)',
  				'col' => 'moq_set_of', 
  				'parent' => 'title_moq',
  				'background_color'=>'FFBFBFBF'),
	 		'price.cn_vat_price' => array('txt'=>'RMB VAT Price',
	 			'show_type' => 'fun',
	  			'fun' => 'function($data){return "￥".$data["price"]["cn_vat_price"];};',
  				'background_color'=>'FF538DD5','parent' => 'title_china'),
	 		'price.cn_freight' => array('txt'=>'Freight','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_freight"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_vat' => array('txt'=>'VAT','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_vat"]."%";};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_load' => array('txt'=>'Load','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_load"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_mpf' => array('txt'=>'MPF','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_mpf"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_hmf' => array('txt'=>'HMF','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_hmf"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_elc' => array('txt'=>'ELC','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_elc"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_ashleycost' => array('txt'=>'Ashley cost','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_ashley_cost"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_retail' => array('txt'=>'China Retail','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_retail"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_imu' => array('txt'=>'IMU','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_imu"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_initial_buy' => array('txt'=>'Initial Buy per Store','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_initial_buy"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.cn_total_pieces' => array('txt'=>'Total China pieces','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["cn_total_pieces"];};',
  				'background_color'=>'FF538DD5', 
  				'parent' => 'title_china'),
	 		'price.us_fob_price' => array('txt'=>'FOB US Price','show_type' => 'fun',
	  			'fun' => 'function($data){return "$".$data["price"]["us_fob_price"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_freight' => array('txt'=>'Freight','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_freight"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_duty' => array('txt'=>'Duty','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_duty"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_misc' => array('txt'=>'Misc','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_misc"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_load' => array('txt'=>'Load','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_load"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_mpf' => array('txt'=>'MPF','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_mpf"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_hmf' => array('txt'=>'HMF','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_hmf"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_elc' => array('txt'=>'ELC','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_elc"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
  			'price.us_ashleycost' => array('txt'=>'Ashley cost','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_ashley_cost"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_retail' => array('txt'=>'US Retail','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_retail"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_imu' => array('txt'=>'IMU','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_imu"];};',
  				'background_color'=>'FF92D050', 'parent' => 'title_us'),
	 		'price.us_initial_buy' => array('txt'=>'Initial Buy per Store','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_initial_buy"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'price.us_total_pieces' => array('txt'=>'Total US pieces','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["price"]["us_total_pieces"];};',
  				'background_color'=>'FF92D050', 
  				'parent' => 'title_us'),
	 		'item_dimension.w' => array('txt'=>'W','show_type' => 'fun',
	  			'fun' => 'function($data){$rtn = trim($data["unit_w"]);if(is_numeric($rtn)) $rtn=number_format($rtn,3);$data["unit"]== "MM" AND $rtn="MM:".$rtn;return $rtn;};',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_item_dimension'),
	 		'item_dimension.d' => array('txt'=>'D','show_type' => 'fun',
	  			'fun' => 'function($data){$rtn = trim($data["unit_d"]);if(is_numeric($rtn)) $rtn=number_format($rtn,3);$data["unit"]== "MM" AND $rtn="MM:".$rtn;return $rtn;};',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_item_dimension'),
	 		'item_dimension.h' => array('txt'=>'H','show_type' => 'fun',
	  			'fun' => 'function($data){$rtn = trim($data["unit_h"]);if(is_numeric($rtn)) $rtn=number_format($rtn,3);$data["unit"]== "MM" AND $rtn="MM:".$rtn;return $rtn;};',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_item_dimension'),
	 		'packerinfo_inner' => array('txt'=>'inner','show_type' => 'col',
	  			'col' => 'unit_pack_inner',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_unit_pack'),
	 		'packerinfo_master' => array('txt'=>'master','show_type' => 'col',
	  			'col' => 'unit_pack_master',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_unit_pack'),
  			'shipping.w' => array('txt'=>'W','show_type' => 'fun',
	  			'fun' => 'function($data){$rtn = trim($data["shipping"]["unit_w"]);if(is_numeric($rtn)) $rtn=number_format($rtn,3);$data["unit"]== "MM" AND $rtn="MM:".$rtn;return $rtn;};',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_master_dimension'),
	 		'shipping.d' => array('txt'=>'D','show_type' => 'fun',
	  			'fun' => 'function($data){$rtn = trim($data["shipping"]["unit_d"]);if(is_numeric($rtn)) $rtn=number_format($rtn,3);$data["unit"]== "MM" AND $rtn="MM:".$rtn;return $rtn;};',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_master_dimension'),
	 		'shipping.h' => array('txt'=>'H','show_type' => 'fun',
	  			'fun' => 'function($data){$rtn = trim($data["shipping"]["unit_h"]);if(is_numeric($rtn)) $rtn=number_format($rtn,3);$data["unit"]== "MM" AND $rtn="MM:".$rtn;return $rtn;};',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_master_dimension'),
	 		'shipping.carton_weight_nw' => array('txt'=>'N.W','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["shipping"]["carton_weight_nw"];};',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_master_carton_weight'),
	 		'shipping.carton_weight_gw' => array('txt'=>'G.W','show_type' => 'fun',
	  			'fun' => 'function($data){return $data["shipping"]["carton_weight_gw"];};',
  				'background_color'=>'FFE26B0A',
  				'parent' => 'title_master_carton_weight')
  		)
  	)
);